declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_L2_RPC_URL: string;
    NEXT_PUBLIC_AI_ORACLE_ADDRESS: string;
    NEXT_PUBLIC_AI_ORACLE_ADDRESS_ETHEREUM_SEPOLIA: string;
    NEXT_PUBLIC_AI_ORACLE_ADDRESS_ETHEREUM_MAINNET: string;
    NEXT_PUBLIC_AI_ORACLE_ADDRESS_OPTIMISM_SEPOLIA: string;
    NEXT_PUBLIC_AI_ORACLE_ADDRESS_OPTIMISM_MAINNET: string;
    NEXT_PUBLIC_AI_PROMPT_ADDRESS: string;
    NEXT_PUBLIC_AI_PROMPT_ADDRESS_ETHEREUM_SEPOLIA: string;
    NEXT_PUBLIC_AI_PROMPT_ADDRESS_ETHEREUM_MAINNET: string;
    NEXT_PUBLIC_AI_PROMPT_ADDRESS_OPTIMISM_SEPOLIA: string;
    NEXT_PUBLIC_AI_PROMPT_ADDRESS_OPTIMISM_MAINNET: string;
    NEXT_PUBLIC_AI_SIMPLE_PROMPT_ADDRESS: string;
    NEXT_PUBLIC_AI_SIMPLE_PROMPT_ADDRESS_ETHEREUM_SEPOLIA: string;
    NEXT_PUBLIC_AI_SIMPLE_PROMPT_ADDRESS_ETHEREUM_MAINNET: string;
    NEXT_PUBLIC_AI_SIMPLE_PROMPT_ADDRESS_OPTIMISM_SEPOLIA: string;
    NEXT_PUBLIC_AI_SIMPLE_PROMPT_ADDRESS_OPTIMISM_MAINNET: string;
    NEXT_PUBLIC_WALLET_ADDRESS: string;
  }
}
